### PR TITLE
Adding 'dxansible' to webhook to run github-CD-checks job

### PR DESCRIPTION
**Pull request by babineaum**

### CODE REVIEW

**Comment by ferrants** [comment]
we should put this file in dxansible

we should just do it for all repos so we don't need to make this change and deploy each time we want to add one

**Comment by babineaum** [comment]
was going to work on that this week matt. after we get this in ill take care of it.

**Comment by babineaum** [comment]
Not sure about turning this on for all repos. If we do that we will have lots of builds of this job spinning up and not performing any actions because there are no required status checks.
Is this something we want?

**Comment by ferrants** [comment]
I think we should have it for all repos. It only gets triggered when someone types `:shipit:` and then you don't need to do a new deploy for each time you want to let a new repo pick it up. Is the concern API limits or that it's not robust enough to handle that amount of traffic or something else?

**Comment by babineaum** [comment]
Concern was running the job so much for inactivity. Api limits shouldn't be that big of an issue, since Peter's refactor the other day, performing only 1 github-pr call and then a few more. I think at most this job does 5 and say maybe there are MAX 30 PRs shipped in a day. then this shouldn't be fired too much. The job/jenkins/webhooks is pretty robust and can handle amount of traffic.

**Pull request closed without merging**
