### PR TITLE
substring the issue_comment so the list of events looks better

### LINKED ISSUE #28: substring issue comments for the webhooks UI display

### PR DESCRIPTION
**Pull request by dx-pbuckley**
@ferrants this seems to fix #28, let me know what you think (not sure if we want to handle it any differently)

### CODE REVIEW

**Comment by dx-pbuckley** [comment]
screen shot 2015-07-20 at 4 20 39 pm

**Comment by ferrants** [comment]
:+1: :+1:

**Comment by dx-pbuckley** [comment]
Does :+1: + :+1: = :shipit: ? :smile:

**Comment by ferrants** [comment]
:shipit:

**Pull request merged**
