### PR TITLE
removing branch from issue based webhook

### PR DESCRIPTION
**Pull request by babineaum**
Since we don't have a great way to test outside of prod, I just ran across the fact that the "branch" option was not available during an issue action,

So i have removed this branch option from the job

### CODE REVIEW

**Comment by babineaum** [comment]
https://github.com/dataxu/jenkins-jobs/pull/1613 Job i removed branch from

**Comment by babineaum** [comment]
running test deploy to confirm any issues are fixed

**Comment by dx-pbuckley** [comment]
:shipit:

**Comment by babineaum** [comment]
http://172.17.69.27/ up and online here

**Pull request merged**
