### PR TITLE
tighten regex, ignore lookalike master|rel branch

### PR DESCRIPTION
**Pull request by dx-pbuckley**
@ferrants would appreciate a quick look at this, tests are passing locally for me

### CODE REVIEW

**Comment by cchristous** [comment]
looks fine to me

**Comment by ferrants** [comment]
looks good for this, but i think we keep the dx configuration in dxansible now

**Comment by ferrants** [comment]
https://github.com/dataxu/dxansible/blob/master/templates/github-webhooks/map_configs/dx_map_config.yml

**Comment by dx-pbuckley** [comment]
@ferrants I've got those regex changes for the dx configuration here: https://github.com/dataxu/dxansible/pull/2505

**Comment by ferrants** [comment]
:shipit:

**Pull request merged**
